// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateFactor(ctx context.Context, arg CreateFactorParams) (sql.Result, error)
	CreateFactorDetail(ctx context.Context, arg CreateFactorDetailParams) (sql.Result, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (sql.Result, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error)
	DeleteFactor(ctx context.Context, id int64) error
	DeleteFactorDetail(ctx context.Context, id int64) error
	DeleteProduct(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, username string) error
	GetFactor(ctx context.Context, id int64) (Factor, error)
	GetFactorDetail(ctx context.Context, id int64) (FactorDetail, error)
	GetProduct(ctx context.Context, id int64) (Product, error)
	GetUser(ctx context.Context, username string) (User, error)
	ListFactorDetails(ctx context.Context, arg ListFactorDetailsParams) ([]FactorDetail, error)
	ListFactors(ctx context.Context, arg ListFactorsParams) ([]Factor, error)
	ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	UpdateFactor(ctx context.Context, arg UpdateFactorParams) (sql.Result, error)
	UpdateFactorDetail(ctx context.Context, arg UpdateFactorDetailParams) (sql.Result, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (sql.Result, error)
	UpdateProductPresent(ctx context.Context, arg UpdateProductPresentParams) (sql.Result, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (sql.Result, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (sql.Result, error)
}

var _ Querier = (*Queries)(nil)
